syntax = "proto3";

// Configurazione della generazione del codice Java.
option java_multiple_files = true;
option java_package = "com.scuola.apichallenge.grpc";
option java_outer_classname = "FilmProto";

// Definizione del servizio RPC.
service FilmService {
  rpc GetFilms (EmptyRequest) returns (FilmListResponse);
}

// Messaggio vuoto per le richieste senza payload.
message EmptyRequest {}

// Struttura dati del singolo elemento.
message FilmMessage {
  string id = 1;
  string titolo = 2;
  string regista = 3;
  int32 anno = 4;
}

// Array di elementi serializzati.
message FilmListResponse {
  repeated FilmMessage films = 1;
}